# Generated by Django 4.1 on 2022-09-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["-created"]},
        ),
        migrations.RemoveConstraint(
            model_name="answer",
            name="unique_answers_for_question",
        ),
    ]
