# Generated by Django 4.1 on 2022-09-02 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={},
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answer',
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='unique_answered_question_for_users'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.ManyToManyField(to='quiz.answer'),
        ),
    ]
